### ISSUE TITLE
Fine-tuning flex_attention kernel exceeds shared memory limit on Ampere/Ada GPUs (sm_86, sm_89)

### ISSUE THREAD

**Issue by loserbcc** [k2-fsa/OmniVoice#83]
## Bug: Fine-tuning fails on Ampere/Ada GPUs due to flex_attention shared memory requirement

Following `examples/run_finetune.sh` on RTX 4090 and RTX A6000 fails during the first training step with a Triton kernel out-of-resource error. The `flex_attention` kernel used in the training path requires **~128 KB** of shared memory per block, but Ampere (sm_86) and Ada Lovelace (sm_89) consumer/workstation GPUs are capped at **~99 KB** per block. This is a hard hardware limit on these architectures.

### Environment

| | |
|---|---|
| OmniVoice | latest (pip install omnivoice, `main` branch) |
| Python | 3.11.14 |
| torch | 2.8.0+cu126 |
| CUDA runtime | 12.6 |
| triton | 3.4.0 |
| transformers | 5.5.3 |

### Hardware tested (both fail identically)

| GPU | Arch | SM | VRAM | Shared mem/block (optin) |
|-----|------|----|----|-------------------------|
| RTX 4090 | Ada Lovelace | sm_89 | 24 GB | 99 KB (101376 B) |
| RTX A6000 | Ampere | sm_86 | 48 GB | 99 KB (101376 B) |

### Steps to reproduce

```bash
# 1. Prepare JSONL manifest: {"id", "audio_path", "text", "language_id"}
# 2. Tokenize
python -m omnivoice.scripts.extract_audio_tokens \
  --input_jsonl train.jsonl \
  --tar_output_pattern data/train/audios/shard-%06d.tar \
  --jsonl_output_pattern data/train/txts/shard-%06d.jsonl

# 3. Launch training with official finetune config
accelerate launch --gpu_ids 0 --num_processes 1 --mixed_precision bf16 \
  -m omnivoice.cli.train \
  --train_config config/train_config_finetune.json \
  --data_config config/data_config_finetune.json \
  --output_dir checkpoints
```

Model loads successfully, trainer enters `Training Loop...`, then fails on first step.

### Error

```
torch._inductor.exc.InductorError: RuntimeError: No valid triton configs.
OutOfMemoryError: out of resource: triton_tem_fused_0
Required: 131328  Hardware limit: 101376
Reducing block sizes or `num_stages` may help.
```

The call site is in transformers' flex_attention integration:
```
File ".../transformers/integrations/flex_attention.py", line 317, in flex_attention_forward
  flex_attention_output = compile_friendly_flex_attention(...)
File ".../transformers/integrations/flex_attention.py", line 124, in compile_friendly_flex_attention
  return flex_attention_compiled(...)
```

Triggered during the training forward pass (inference with `attn_implementation="flex_attention"` works fine because the inference kernel uses smaller blocks).

### Root cause

`attn_implementation="flex_attention"` is hardcoded in `omnivoice/training/builder.py`:

```python
model = OmniVoice.from_pretrained(
    config.init_from_checkpoint,
    attn_implementation="flex_attention",
    dtype=torch.float32,
    train=True,
)
```

The Triton kernel for the training-mode flex_attention autotunes to a block size (128×128 or similar) that requires ~128 KB shared memory per block. Shared memory limits by architecture:

| Arch | Max optin shared/block |
|------|------------------------|
| sm_80 (A100) | 164 KB ✅ |
| sm_86 (A6000/3090) | 99 KB ❌ |
| sm_89 (4090) | 99 KB ❌ |
| sm_90 (H100) | 228 KB ✅ |
| sm_100+ (Blackwell) | 228 KB ✅ |

This means fine-tuning is currently only possible on A100 / H100 / Blackwell — every other consumer or workstation card will fail.

### What I tried

- `attn_implementation="sdpa"` → `ValueError: OmniVoice does not support an attention implementation through torch.nn.functional.scaled_dot_product_attention yet`
- `attn_implementation="eager"` → loads but OOMs on 24 GB even with `batch_tokens: 1024`
- `TORCHDYNAMO_DISABLE=1` with `flex_attention` → SIGSEGV (flex_attention requires torch.compile internally)
- Reducing `batch_tokens` from 8192 → 4096 → 2048 → 1024 — no effect (kernel block size is independent of batch tokens)

### Expected behavior

One of:
1. **Reduce training kernel block size** so it fits within 99 KB shared memory on Ampere/Ada
2. **Add SDPA attention support** for the training path as a fallback
3. **Document the datacenter GPU requirement** (A100 / H100 / Blackwell) in the fine-tuning README so users don't waste time setting up on consumer cards

Happy to test any fix on 4090 / A6000 / (soon) Blackwell. Thanks for the great model — inference works beautifully and the 600+ language coverage is impressive!

**Comment by zhu-han** [comment]
Thanks for reporting it, will add a SDPA attention support.

**Comment by lnqaq** [comment]
same here

**Comment by lumpidu** [comment]
We have found a workaround. Force smaller Triton block sizes via `kernel_options`.

Monkey-patch `compile_friendly_flex_attention` before model init:

```python
kernel_options = {
      "BLOCK_M": 32, "BLOCK_N": 32,
      "BLOCK_M1": 32, "BLOCK_N1": 32,
      "BLOCK_M2": 32, "BLOCK_N2": 32,
      "num_stages": 2, "num_warps": 4,
  }
```

Pinning only `BLOCK_M/BLOCK_N` is not enough — Triton's autotuner then increases num_stages and shared memory usage actually grows. All axes must be pinned !

With `head_dim=128` (as in Qwen3-0.6B), `64×64` blocks are still too large, `32×32` fits within 99 KB.

Tested on 2× RTX A6000 (aka sm_86), batch_tokens=8192, bf16

Verbose:

```python
# Apply before build_model_and_tokenizer()
import transformers.integrations.flex_attention as fa

original = fa.compile_friendly_flex_attention
kernel_opts = {
   "BLOCK_M": 32, "BLOCK_N": 32,
   "BLOCK_M1": 32, "BLOCK_N1": 32,
   "BLOCK_M2": 32, "BLOCK_N2": 32,
   "num_stages": 2, "num_warps": 4,
}

def _patched(query, key, value, training=False, **kwargs):
    opts = dict(kwargs.get("kernel_options") or {})
    for k, v in kernel_opts.items():
        opts.setdefault(k, v)
    kwargs["kernel_options"] = opts
    return original(query, key, value, training=training, **kwargs)

fa.compile_friendly_flex_attention = _patched
```

**Comment by lumpidu** [comment]
We have also tried SDPA: this slows training down considerably (5x slower). Flex attention is the way to go here.

**Comment by loserbcc** [comment]
Confirmed the monkey-patch workaround from @lumpidu works on additional hardware:

**NVIDIA RTX PRO 6000 Blackwell Workstation Edition (sm_120)**
- Shared memory per block: **99 KB** (same consumer limit as Ampere/Ada — workstation Blackwell does NOT get datacenter-class 163KB+)
- torch 2.9.0+cu128, torchaudio 2.9.0+cu128, Python 3.12
- 96 GB VRAM — plenty of headroom for fine-tuning

The 32×32 block patch runs without issues. Trained 3000 steps on a 240-sample dataset with no kernel errors.

**Small-dataset recipe that avoids overfitting** (we hit catastrophic overfitting on the defaults):

| Setting | Default | Tuned |
|---------|---------|-------|
| `learning_rate` | 5e-5 | **1e-5** |
| `repeat` | 10 | **3** |
| `warmup_ratio` | 0.01 | **0.05** |
| `batch_tokens` | 1024 | **4096** (if VRAM allows) |
| `gradient_accumulation_steps` | 8 | **2** |
| `save_steps` | 500 | **100** |

With defaults (LR 5e-5, repeat 10), quality collapses after ~500 steps on a 240-sample set. With the tuned config, checkpoints stay clean through 1500+ steps.

For reference, the `num_workers` in train config must be ≤ shard count in your WebDataset or you'll get `No samples found in dataset`.

**Comment by HalfienP** [comment]
@loserbcc @lumpidu Hi, can you help me with this issue? ```torch._dynamo.exc.InternalTorchDynamoError:
NotImplementedError: TensorVariable() is not a constant
...File omnivoice/models/omnivoice.py", line 385, in forward
attention_mask = create_block_mask(``` ```attention_mask = create_block_mask(...)
torch/nn/attention/flex_attention.py``` When I try to finetune on GPU A100, will Monkey-patch compile_friendly_flex_attention help fix this error? Can you suggest Python, Torch, and CUDA versions for my case (now Python 3.10 | PyTorch 2.5.1+cu121 | CUDA 12.1)? I'm not sure if my error is similar to this issue. And what steps-per-second rate is considered good for the performance of an A100 GPU?

> Confirmed the monkey-patch workaround from [@lumpidu](https://github.com/lumpidu) works on additional hardware:
> 
> **NVIDIA RTX PRO 6000 Blackwell Workstation Edition (sm_120)**
> 
>     * Shared memory per block: **99 KB** (same consumer limit as Ampere/Ada — workstation Blackwell does NOT get datacenter-class 163KB+)
> 
>     * torch 2.9.0+cu128, torchaudio 2.9.0+cu128, Python 3.12
> 
>     * 96 GB VRAM — plenty of headroom for fine-tuning
> 
> 
> The 32×32 block patch runs without issues. Trained 3000 steps on a 240-sample dataset with no kernel errors.
> 
> **Small-dataset recipe that avoids overfitting** (we hit catastrophic overfitting on the defaults):
> Setting 	Default 	Tuned
> `learning_rate` 	5e-5 	**1e-5**
> `repeat` 	10 	**3**
> `warmup_ratio` 	0.01 	**0.05**
> `batch_tokens` 	1024 	**4096** (if VRAM allows)
> `gradient_accumulation_steps` 	8 	**2**
> `save_steps` 	500 	**100**
> 
> With defaults (LR 5e-5, repeat 10), quality collapses after ~500 steps on a 240-sample set. With the tuned config, checkpoints stay clean through 1500+ steps.
> 
> For reference, the `num_workers` in train config must be ≤ shard count in your WebDataset or you'll get `No samples found in dataset`.

**Comment by zhu-han** [comment]
Now we also support fine-tuning with SDPA. Use the `examples/config/train_config_finetune_sdpa.json` config file if you encounter issues with flex_attention.

**Comment by hazartilirot** [comment]
**Confirmed on 2× RTX 3090 (sm_86, 24 GB each)**

Same issue here. OmniVoice 0.1.3, torch 2.8.0+cu128, transformers 5.5.4, triton latest.
Tried everything listed by OP plus:

Patching builder.py to pass attn_implementation="sdpa" → ValueError: OmniVoice does not support SDPA
Patching builder.py for "eager" → TypeError: unsupported operand type(s) for +: 'Tensor' and 'BlockMask' (forward() still creates BlockMask)
Patching omnivoice.py forward() to generate standard attention mask + setting _attn_implementation="sdpa" per layer → Triton still triggers via torch.compile
TORCHDYNAMO_DISABLE=1 → same Triton error

The train_config_finetune_sdpa.json config exists but is completely ignored — builder.py hardcodes flex_attention. This makes fine-tuning impossible on any consumer/workstation GPU.
Really need a proper SDPA/eager training path. Happy to test any fix on 2× 3090.

**Comment by hazartilirot** [comment]
[lumpidu](https://github.com/lumpidu)

🤘🤘🤘🤘🤘🤘🤘 Hallelujah 

<img width="2023" height="1211" alt="Image" src="https://github.com/user-attachments/assets/9dbc636a-9aba-474b-a2f4-1e1fbec1db5a" />

**Comment by zhu-han** [comment]
> **Confirmed on 2× RTX 3090 (sm_86, 24 GB each)**
> 
> Same issue here. OmniVoice 0.1.3, torch 2.8.0+cu128, transformers 5.5.4, triton latest. Tried everything listed by OP plus:
> 
> Patching builder.py to pass attn_implementation="sdpa" → ValueError: OmniVoice does not support SDPA Patching builder.py for "eager" → TypeError: unsupported operand type(s) for +: 'Tensor' and 'BlockMask' (forward() still creates BlockMask) Patching omnivoice.py forward() to generate standard attention mask + setting _attn_implementation="sdpa" per layer → Triton still triggers via torch.compile TORCHDYNAMO_DISABLE=1 → same Triton error
> 
> The train_config_finetune_sdpa.json config exists but is completely ignored — builder.py hardcodes flex_attention. This makes fine-tuning impossible on any consumer/workstation GPU. Really need a proper SDPA/eager training path. Happy to test any fix on 2× 3090.

Use the latest code if you want to use SDPA training instead of flex_attention, OmniVoice 0.1.3 is a old version that does not support SDPA training.

**Comment by loserbcc** [comment]
Different root cause from the sm_120 case but same patch helps.

`TensorVariable() is not a constant` is a known torch.compile/dynamo failure on PyTorch 2.5.1 with FlexAttention's `create_block_mask`, not a shared-memory issue. A100 has 163 KB shared mem (vs 99 KB on consumer cards), so you don't need the 32×32 override for fit — but the monkey-patch intercepts the same call site and dodges the dynamo error.

Recommended:

| Component | Yours       | Try                       |
|-----------|-------------|---------------------------|
| Python    | 3.10        | 3.10 OK, 3.12 known-good  |
| PyTorch   | 2.5.1+cu121 | **2.9.0+cu128** (or ≥2.7) |
| CUDA      | 12.1        | 12.4 / 12.8               |

If the upgrade alone doesn't resolve it, apply the monkey-patch (harmless on A100 — the smaller blocks just under-utilize your 163 KB SM, you'll lose a bit of throughput but it'll run).

Don't have an A100 steps/sec datapoint handy; ran on a rented A100 back in April but didn't log throughput. Anyone else have numbers?
